excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://mridulganga.github.io
title: ONYX Campus Venture
tagline: Lets start a venture
description: This is a site dedicated to campus ventures in ONYX
paginate: 5